---
abstract: 'simple password generation and assessment'
author:
  - 'Dominik Schulz <dominik.schulz@gauner.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Pwgen
requires:
  perl: 5.008
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/gittex/Data-Pwgen/issues
  repository: git://github.com/gittex/Data-Pwgen.git
version: 0.12
x_authority: cpan:TEX
